import React, { useEffect, useState } from 'react';
import { X, Copy, Download, Code2 } from 'lucide-react';
import { useStore } from '../store/useStore';

interface SQLPreviewModalProps {
    isOpen: boolean;
    onClose: () => void;
    tableName: string;
}

// Basic regex-based SQL syntax highlighter
const highlightSQL = (sql: string) => {
    let highlighted = sql;

    // Highlight strings
    highlighted = highlighted.replace(/'([^']*)'/g, '<span class="text-green-600">\'$1\'</span>');
    highlighted = highlighted.replace(/"([^"]*)"/g, '<span class="text-green-700">"$1"</span>');

    // Highlight keywords
    const keywords = [
        'SELECT', 'FROM', 'WHERE', 'AND', 'OR', 'AS', 'CAST', 'GROUP BY',
        'ORDER BY', 'LIMIT', 'JOIN', 'LEFT', 'RIGHT', 'INNER', 'ON', 'WITH',
        'OVER', 'PARTITION BY', 'SUM', 'COUNT', 'AVG', 'MIN', 'MAX', 'CASE', 'WHEN', 'THEN', 'ELSE', 'END'
    ];

    keywords.forEach(kw => {
        const regex = new RegExp(`\\b${kw}\\b`, 'gi');
        highlighted = highlighted.replace(regex, (match) => `<span class="text-blue-600 font-bold">${match.toUpperCase()}</span>`);
    });

    // Highlight numbers
    highlighted = highlighted.replace(/\b(\d+(?:\.\d+)?)\b/g, '<span class="text-orange-500">$1</span>');

    return highlighted;
};

export default function SQLPreviewModal({ isOpen, onClose, tableName }: SQLPreviewModalProps) {
    const { rebuildPipelineQuery, copyPipelineSQL, exportPipelineSQL } = useStore();
    const [sqlContent, setSqlContent] = useState('');

    useEffect(() => {
        if (isOpen && tableName) {
            try {
                const baseQuery = `SELECT * FROM "${tableName}"`;
                const rawSQL = rebuildPipelineQuery(tableName, baseQuery);
                // Format slightly
                const formatted = `-- Pipeline SQL for table: ${tableName}\n-- Generated at: ${new Date().toISOString()}\n\n${rawSQL};\n`;
                setSqlContent(formatted);
            } catch (err) {
                setSqlContent('-- Error generating SQL');
            }
        }
    }, [isOpen, tableName, rebuildPipelineQuery]);

    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
            {/* Backdrop */}
            <div
                className="absolute inset-0 bg-stone-900/40 dark:bg-black/60 backdrop-blur-sm animate-in fade-in duration-300"
                onClick={onClose}
            />

            {/* Modal Content */}
            <div className="relative w-full max-w-3xl bg-white dark:bg-[#1a1a1a] rounded-2xl shadow-2xl dark:shadow-black/60 border border-stone-200 dark:border-white/10 overflow-hidden flex flex-col max-h-[85vh] animate-in fade-in zoom-in-95 duration-200 transition-colors">
                <div className="px-6 py-4 flex items-center justify-between border-b border-stone-100 dark:border-white/10 bg-stone-50/50 dark:bg-[#141414] shrink-0 transition-colors">
                    <div className="flex items-center gap-2 text-stone-800 dark:text-stone-200 font-semibold text-lg">
                        <div className="w-8 h-8 rounded-lg bg-indigo-100 dark:bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 flex items-center justify-center shadow-sm">
                            <Code2 size={18} />
                        </div>
                        Preview SQL
                    </div>
                    <button
                        onClick={onClose}
                        title="Close"
                        className="text-stone-400 dark:text-stone-500 hover:text-stone-600 dark:hover:text-stone-300 p-1 rounded-full hover:bg-stone-100 dark:hover:bg-white/10 transition-colors"
                    >
                        <X size={20} />
                    </button>
                </div>

                <div className="flex-1 p-6 overflow-hidden flex flex-col gap-4">
                    <div className="text-sm text-stone-600 dark:text-stone-400">
                        This is the raw SQL generated by your transformation pipeline for <strong className="dark:text-stone-200">{tableName}</strong>.
                    </div>

                    <div className="flex-1 relative rounded-xl border border-stone-200 bg-stone-900 overflow-hidden shadow-inner flex flex-col">
                        <div className="flex items-center justify-end gap-2 p-2 bg-stone-800 border-b border-stone-700 shrink-0">
                            <button
                                onClick={() => copyPipelineSQL(tableName)}
                                className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-stone-300 hover:text-white hover:bg-stone-700 rounded-md transition-colors"
                            >
                                <Copy size={14} />
                                Copy
                            </button>
                            <button
                                onClick={() => exportPipelineSQL(tableName)}
                                className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-stone-300 hover:text-white hover:bg-stone-700 rounded-md transition-colors"
                            >
                                <Download size={14} />
                                Download
                            </button>
                        </div>

                        <div className="flex-1 overflow-auto p-4 custom-scrollbar">
                            <pre className="text-sm font-mono text-stone-300 whitespace-pre-wrap break-all leading-relaxed">
                                <code dangerouslySetInnerHTML={{ __html: highlightSQL(sqlContent) }} />
                            </pre>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
